export const ReasonCodes = {
  APPROVED: "APPROVED",
  UNVERIFIED: "UNVERIFIED",
  CUSTODY_PROTECTED: "CUSTODY_PROTECTED",
  UNKNOWN_OBJECT_STATE: "UNKNOWN_OBJECT_STATE",
  EXECUTION_DENIED: "EXECUTION_DENIED",
  REGULATORY_COMPLIANCE_HOLD: "REGULATORY_COMPLIANCE_HOLD",
  EVIDENCE_MISSING: "EVIDENCE_MISSING",
  UNKNOWN_ACTION: "UNKNOWN_ACTION",
  UNKNOWN_POLICY: "UNKNOWN_POLICY",
  MISSING_ENVELOPE: "MISSING_ENVELOPE",
  MISSING_PROVENANCE: "MISSING_PROVENANCE",
  INVALID_EVIDENCE_REF: "INVALID_EVIDENCE_REF"
};

export default ReasonCodes;
