import test from 'node:test';
import assert from 'node:assert/strict';
import { GovernedVoicePipeline } from '../../src/voice/pipeline/governedVoicePipeline.js';
import corpus from './corpus/wenger-voice-corpus.json' with { type: 'json' };

test('Governed Voice Pipeline: Full End-to-End Turn Execution across Corpus', async () => {
  const pipeline = new GovernedVoicePipeline();

  for (const item of corpus.utterances) {
    const turnResult = await pipeline.processVoiceTurn({
      audio_buffer: new Uint8Array(32000),
      expected_text: item.text
    }, {
      mode: "COMPETE",
      athlete_consent: true,
      human_supervision: true,
      career_opt_in: true
    });

    assert.equal(turnResult.status, "SUCCESS");
    assert.equal(turnResult.transcript, item.text);
    assert.ok(turnResult.canonical_text.length > 0);
    assert.ok(turnResult.evidence.canonical_text_hash.startsWith("sha256-"));
    assert.ok(turnResult.timestamps.total_ms > 0);
  }
});

test('Governed Voice Pipeline: Canonical Text Authority Guarantee', async () => {
  const pipeline = new GovernedVoicePipeline();

  const turn = await pipeline.processVoiceTurn("Teeing off on hole 1.", {
    mode: "COMPETE",
    athlete_consent: true,
    human_supervision: true,
    career_opt_in: true
  });

  // Canonical text generated by Article 19 engine is identical to voice rendering source
  assert.equal(turn.voice_rendering.rendered_text.includes(turn.canonical_text), true);
  assert.ok(turn.evidence.canonical_response_text === turn.canonical_text);
});
