export const CatalogAssets = [
  {
    asset_id: "urn:davincia:knowledge:asset:brehon-ip",
    title: "Brehon Decentralized Governance IP Model",
    owner: "urn:davincia:identity:organization:brehon_ai",
    description: "Decentralized legal and constitutional governance framework rules translation.",
    asset_class: "DOCUMENT",
    provenance_hash: "sha256-brehon-ip-prov",
    version: "1.0.0",
    sensitivity: "PUBLIC",
    permitted_actions: ["READ", "SEARCH"],
    prohibited_actions: ["TRANSFORM"],
    governance_policy: "DAVINCIA-CULTURAL-003",
    pricing_plan: "urn:davincia:pricing:brehon-usage-v1",
    license_id: "urn:davincia:license:brehon-commercial-v1",
    currency: "USD",
    status: "ACTIVE",
    created_at: "2026-08-28T12:00:00Z",
    updated_at: "2026-08-30T12:00:00Z"
  },
  {
    asset_id: "urn:davincia:knowledge:asset:munster-slang",
    title: "Munster Slang and Cant Dictionary",
    owner: "urn:davincia:identity:organization:brehon_ai",
    description: "Vernacular slang database and regional glossary translation vectors.",
    asset_class: "DATASET",
    provenance_hash: "sha256-munster-slang-prov",
    version: "1.2.0",
    sensitivity: "PUBLIC_RESTRICTED",
    permitted_actions: ["READ", "TRANSLATE"],
    prohibited_actions: ["PUBLISH"],
    governance_policy: "DAVINCIA-CULTURAL-003",
    pricing_plan: "urn:davincia:pricing:slang-fixed-v1",
    license_id: "urn:davincia:license:slang-educational-v1",
    currency: "EUR",
    status: "ACTIVE",
    created_at: "2026-08-28T12:00:00Z",
    updated_at: "2026-08-30T12:00:00Z"
  },
  {
    asset_id: "urn:davincia:knowledge:asset:arios-security",
    title: "ARIOS Execution Security Guidelines",
    owner: "urn:davincia:identity:organization:arios_corp",
    description: "Sovereign operating system agent execution custody boundaries.",
    asset_class: "SOFTWARE",
    provenance_hash: "sha256-arios-security-prov",
    version: "2.1.0",
    sensitivity: "SENSITIVE_PROTECTED",
    permitted_actions: ["READ", "INFER"],
    prohibited_actions: ["EXECUTE"],
    governance_policy: "DAVINCIA-OS-002",
    pricing_plan: "urn:davincia:pricing:arios-subscription-v1",
    license_id: "urn:davincia:license:arios-enterprise-v1",
    currency: "USD",
    status: "ACTIVE",
    created_at: "2026-08-29T11:00:00Z",
    updated_at: "2026-08-30T12:00:00Z"
  },
  {
    asset_id: "urn:davincia:knowledge:asset:marine-cables",
    title: "Global Marine Subsea Cable Registry",
    owner: "urn:davincia:identity:organization:telecom_assoc",
    description: "Fiber-optic submarine cable landing points and routing datasets.",
    asset_class: "DATASET",
    provenance_hash: "sha256-marine-cables-prov",
    version: "1.0.0",
    sensitivity: "PUBLIC",
    permitted_actions: ["READ", "SEARCH"],
    prohibited_actions: ["EXPORT"],
    governance_policy: "DAVINCIA-INFRA-001",
    pricing_plan: "urn:davincia:pricing:cables-usage-v1",
    license_id: "urn:davincia:license:cables-standard-v1",
    currency: "USD",
    status: "ACTIVE",
    created_at: "2026-08-29T12:00:00Z",
    updated_at: "2026-08-30T12:00:00Z"
  },
  {
    asset_id: "urn:davincia:knowledge:asset:datacenters",
    title: "Global Datacenter Inventory Registry",
    owner: "urn:davincia:identity:organization:datacenter_consortium",
    description: "Co-location server hubs and hyperscale physical facility metadata.",
    asset_class: "DATASET",
    provenance_hash: "sha256-datacenters-prov",
    version: "1.0.0",
    sensitivity: "PUBLIC",
    permitted_actions: ["READ", "SEARCH"],
    prohibited_actions: ["DELETE"],
    governance_policy: "DAVINCIA-INFRA-002",
    pricing_plan: "urn:davincia:pricing:datacenters-usage-v1",
    license_id: "urn:davincia:license:datacenters-standard-v1",
    currency: "USD",
    status: "ACTIVE",
    created_at: "2026-08-29T12:00:00Z",
    updated_at: "2026-08-30T12:00:00Z"
  },
  {
    asset_id: "urn:davincia:knowledge:asset:natural-earth",
    title: "Natural Earth Geographic Boundaries",
    owner: "urn:davincia:identity:organization:cartographic_society",
    description: "Sovereign land boundary vector polygons and country boundaries.",
    asset_class: "DATASET",
    provenance_hash: "sha256-natural-earth-prov",
    version: "3.2.0",
    sensitivity: "PUBLIC",
    permitted_actions: ["READ", "SEARCH", "SHARE"],
    prohibited_actions: ["TRANSFORM"],
    governance_policy: "DAVINCIA-MAP-001",
    pricing_plan: "urn:davincia:pricing:free-plan-v1",
    license_id: "urn:davincia:license:public-domain-v1",
    currency: "USD",
    status: "ACTIVE",
    created_at: "2026-08-29T12:00:00Z",
    updated_at: "2026-08-30T12:00:00Z"
  },
  {
    asset_id: "urn:davincia:knowledge:asset:neighborhoods",
    title: "San Francisco Neighborhood Geographic Polygons",
    owner: "urn:davincia:identity:organization:sf_city_planning",
    description: "Urban planning boundaries and local municipality district geojsons.",
    asset_class: "DATASET",
    provenance_hash: "sha256-neighborhoods-prov",
    version: "1.0.0",
    sensitivity: "PUBLIC",
    permitted_actions: ["READ", "SEARCH"],
    prohibited_actions: ["TRANSFORM"],
    governance_policy: "DAVINCIA-MAP-002",
    pricing_plan: "urn:davincia:pricing:neighborhoods-fixed-v1",
    license_id: "urn:davincia:license:sf-planning-v1",
    currency: "USD",
    status: "ACTIVE",
    created_at: "2026-08-29T12:00:00Z",
    updated_at: "2026-08-30T12:00:00Z"
  },
  {
    asset_id: "urn:davincia:knowledge:asset:weather-service",
    title: "Embassy Weather Observer Service",
    owner: "urn:davincia:identity:organization:met_office",
    description: "Real-time atmospheric radar vectors and cloud cover APIs.",
    asset_class: "API",
    provenance_hash: "sha256-weather-service-prov",
    version: "4.0.0",
    sensitivity: "PUBLIC",
    permitted_actions: ["READ", "SEARCH"],
    prohibited_actions: ["ARCHIVE"],
    governance_policy: "DAVINCIA-SERVICE-001",
    pricing_plan: "urn:davincia:pricing:weather-usage-v1",
    license_id: "urn:davincia:license:weather-standard-v1",
    currency: "USD",
    status: "ACTIVE",
    created_at: "2026-08-29T12:00:00Z",
    updated_at: "2026-08-30T12:00:00Z"
  },
  {
    asset_id: "urn:davincia:knowledge:asset:voice-generator",
    title: "Embassy Speech Synthesizer Model",
    owner: "urn:davincia:identity:organization:voice_labs",
    description: "Standard vs Mini voice generation text-to-speech engine.",
    asset_class: "API",
    provenance_hash: "sha256-voice-generator-prov",
    version: "1.1.0",
    sensitivity: "PUBLIC",
    permitted_actions: ["READ", "INFER"],
    prohibited_actions: ["TRAIN"],
    governance_policy: "DAVINCIA-MODEL-001",
    pricing_plan: "urn:davincia:pricing:voice-usage-v1",
    license_id: "urn:davincia:license:voice-standard-v1",
    currency: "USD",
    status: "ACTIVE",
    created_at: "2026-08-29T12:00:00Z",
    updated_at: "2026-08-30T12:00:00Z"
  },
  {
    asset_id: "urn:davincia:knowledge:asset:refinery-pipeline",
    title: "Strata Refinery Ingestion Software Suite",
    owner: "urn:davincia:identity:organization:brehon_ai",
    description: "Raw to Governed document asset packaging batch refinery compiler.",
    asset_class: "SOFTWARE",
    provenance_hash: "sha256-refinery-pipeline-prov",
    version: "1.0.0",
    sensitivity: "PUBLIC_RESTRICTED",
    permitted_actions: ["READ", "EXECUTE"],
    prohibited_actions: ["PUBLISH"],
    governance_policy: "DAVINCIA-OS-001",
    pricing_plan: "urn:davincia:pricing:refinery-royalty-v1",
    license_id: "urn:davincia:license:refinery-royalty-v1",
    currency: "USD",
    status: "ACTIVE",
    created_at: "2026-08-29T12:00:00Z",
    updated_at: "2026-08-30T12:00:00Z"
  }
];

export function lookupCatalogAsset(assetId) {
  return CatalogAssets.find(a => a.asset_id === assetId) || null;
}
